---
- name: Wes-zsh-install
  hosts: localhost
  connection: local
  vars:
    theme: "agnoster" ## make definable later

  tasks:
  - name: "Apt to install zsh"
    ansible.builtin.apt: # module
      name: zsh
      state: present
    become: true # run as root. keyword for task not module

  - name: "Apt to install fonts-powerline"
    ansible.builtin.apt:
      name: fonts-powerline
      state: present
    become: true

  - name: "Download oh-my-zsh"
    ansible.builtin.raw: wget -O oh-my-zsh_install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh 

  - name: "Install oh-my-zsh"
    ansible.builtin.script: ./oh-my-zsh_install.sh --unattended

  - name: "Change default shell"
    ansible.builtin.raw: usermod -s /bin/zsh {{ lookup('env', 'USER') }}

  - name: "Edit plugins"
    lineinfile:
      path: "~/.zshrc"
      regexp: "^plugins=.*"
      line: "plugins=(git colored-man-pages zsh-syntax-highlighting zsh-autosuggestions)"
      backup: true

  - name: "Edit theme"
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.zshrc"
      regexp: "^ZSH_THEME=.*"
      line: 'ZSH_THEME="{{theme}}"'
      backup: true